version: '3'
services:
  devcontainer:
    image:  mcr.microsoft.com/devcontainers/python:1-3.11-bullseye
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:frontend
    command: sleep infinity

  frontend:
    image: ghcr.io/lunarwnderer/huesos-v-banke-upgade:main
    
       
    environment:

      PYTHON_BACKEND_URL: "http://devcontainer:8000"

    restart: unless-stopped
   
   
 